### ISSUE TITLE
[Proposal]: Download slugbuilder image during installation

### ISSUE THREAD

**Issue by aledbf** [deis/builder#177]
Without this additional step the default timeout to wait for a build is not enough and it can fail

`remote: [ERROR] running git receive hook [watching events for builder pod startup (timed out waiting for the condition)]
`

**Comment by arschles** [comment]
@aledbf let's up the timeout for now. I'll take care of doing that and specifying it in an env var (don't remember if it is already).

The alternative is probably to run a Daemonset that does a `docker pull slugbuilder` on all nodes when the deis cluster is first installed. We're not ready for that yet since we'd prefer not to require any features outside of Kubernetes 1.1 core (excluding extensions).
