### ISSUE TITLE
Fork github.com/arschles/assert to the deis org and use that one instead

### ISSUE THREAD

**Issue by arschles** [deis/builder#216]
Ref https://github.com/deis/builder/pull/211#discussion_r54627441

**Comment by bacongobbler** [comment]
I don't think this is an issue we really need to resolve. In fact it's probably better to keep it at your fork for now so that we can keep it up to date in one place. That and we also [pin the package anyways](https://github.com/deis/builder/blob/3c110dd3f9bfc590b27ae98e6364e48eacb1c537/glide.yaml#L27-L28), so we're insulated from `go get` issues that may arise if master was broken.

If problems come up in the future we can consider forking, but let's keep it under your control IMO :)
