### ISSUE TITLE
nodeSelector to run dockerbuilder pod

### ISSUE THREAD

**Issue by arkkanoid** [deis/builder#410]
Deploy an app consumes high CPU, in order to don't affect the deployed apps, I would like to run the dockerbuilder container in an isolate node. 
In the following method the builder component creates the dockerbuilder pod:

https://github.com/deis/builder/blob/96292153e5a52f8ea7643349665f8b3d75a5c1c8/pkg/gitreceive/k8s_util.go#L55

I could add 'nodeselector' parameter in the pod creation, but it means that I'll have a custom Deis component...
There is an esasier way to run this pod in an isolate node?

**Comment by kmala** [comment]
i don't think there is another way than the one you suggested.If you want to make a PR against the builder instead of maintaining you own component, i am happy to help you. You can just add it to the struct https://github.com/deis/builder/blob/master/pkg/gitreceive/config.go#L15 and need to use it if specified while creating the pod.Any one who wan't to use can edit the deis-builder deployment object to add the extra environment variable.

**Comment by kmala** [comment]
this can used to track as an enhancement request
